import React from 'react';
import { ThumbsUp, ThumbsDown, AlertCircle, FileSearch, IndianRupee } from 'lucide-react';

const RecommendationPanel = ({ data }) => {
    // Read the explicit Recommendation Object generated by the Python Ensemble
    const mlDecision = data?.recommendation_payload || {
        final_decision: "Processing...",
        ml_confidence_score: "0%",
        winning_votes: "0/0",
        recommended_limit_inr: 0,
        risk_premium_percentage: 0.0,
        primary_explainable_rationale: "Waiting for backend orchestration..."
    };

    const riskSignals = data?.structured_signals?.structured_financial_analysis?.risk_summary || {};

    let recommendation = mlDecision.final_decision;
    let colorClass = recommendation === 'Approve' ? 'green' : 'red';
    let Icon = recommendation === 'Approve' ? ThumbsUp : ThumbsDown;

    return (
        <div className="max-w-4xl mx-auto px-4 py-8">
            <div className={`bg-white rounded-2xl shadow-lg border-2 border-${colorClass}-100 overflow-hidden`}>
                {/* Header Ribbon */}
                <div className={`bg-${colorClass}-50 px-6 py-4 border-b border-${colorClass}-100 flex items-center justify-between`}>
                    <h2 className="text-xl font-display font-semibold text-gray-900">Final Credit Decision</h2>
                    <span className={`inline-flex items-center space-x-2 px-4 py-2 rounded-full border border-${colorClass}-200 bg-white text-${colorClass}-700 font-bold uppercase tracking-wide text-sm`}>
                        <Icon className="w-5 h-5 mr-1" />
                        {recommendation}
                    </span>
                </div>

                <div className="p-8">
                    <div className="flex flex-col md:flex-row gap-8">

                        {/* Limit Recommendation */}
                        <div className="flex-1 bg-gray-50 rounded-xl p-6 border border-gray-100 flex flex-col justify-center items-center text-center">
                            <p className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-2">Suggested Credit Limit</p>
                            <div className="flex items-center text-gray-900">
                                <IndianRupee className="w-8 h-8 text-gray-400 mr-1" />
                                <span className="text-4xl font-display font-bold">
                                    {mlDecision.recommended_limit_inr.toLocaleString('en-IN')}
                                </span>
                            </div>
                            <div className="mt-4 inline-flex items-center px-3 py-1 bg-blue-50 text-blue-700 text-xs font-bold rounded-full border border-blue-100">
                                {mlDecision.ml_confidence_score} Confidence ({mlDecision.winning_votes} Models Agree)
                            </div>
                        </div>

                        {/* Explanation */}
                        <div className="flex-[2] space-y-4">
                            <h3 className="text-lg font-semibold text-gray-900">Explainable AI Rationale</h3>
                            <p className="text-gray-600 leading-relaxed italic border-l-4 border-gray-200 pl-4 py-1">
                                "{mlDecision.primary_explainable_rationale}"
                            </p>

                            <div className="pt-2">
                                <p className="text-sm font-medium text-gray-500 mb-2">Recommended Risk Premium (ROI): <span className="text-gray-900 font-bold">{mlDecision.risk_premium_percentage}%</span></p>
                            </div>

                            {/* Risk Summary Pills */}
                            <div className="flex flex-wrap gap-2 pt-4 border-t border-gray-100">
                                <span className={`inline-flex items-center px-3 py-1 rounded-full text-xs font-medium ${riskSignals.circular_trading_risk ? 'bg-red-100 text-red-800' : 'bg-green-100 text-green-800'}`}>
                                    Circular Trading
                                </span>
                                <span className={`inline-flex items-center px-3 py-1 rounded-full text-xs font-medium ${riskSignals.revenue_mismatch_risk ? 'bg-red-100 text-red-800' : 'bg-green-100 text-green-800'}`}>
                                    Revenue Match
                                </span>
                                <span className={`inline-flex items-center px-3 py-1 rounded-full text-xs font-medium ${riskSignals.income_inconsistency_risk ? 'bg-yellow-100 text-yellow-800' : 'bg-green-100 text-green-800'}`}>
                                    ITR Consistency
                                </span>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    );
};

export default RecommendationPanel;
